<a href="https://colab.research.google.com/github/jay-D-Deshmukh/EDA-PRO/blob/main/Ridge_Regre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.linear_model import Lasso,LassoCV

In [2]:
boston=pd.read_csv('/content/drive/MyDrive/Data sets/boston-housing-dataset.csv')

In [3]:
boston.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0           0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

     TAX  PTRATIO       B  LSTAT  MEDV  
0  296.0     15.3  396.90   4.98  24.0  
1  242.0     17.8  396.90   9.14  21.6  
2  242.0     17.8  392.83   4.03  34.7  
3  222.0     18.7  394.63   2.94  33.4  
4  222.0     18.7  396.90   5.33  36.2

In [4]:
boston.columns

Index(['Unnamed: 0', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS',
       'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [5]:
X=boston[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE']]
y=boston['MEDV']

In [6]:
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE
0    0.00632  18.0   2.31     0  0.538  6.575  65.2
1    0.02731   0.0   7.07     0  0.469  6.421  78.9
2    0.02729   0.0   7.07     0  0.469  7.185  61.1
3    0.03237   0.0   2.18     0  0.458  6.998  45.8
4    0.06905   0.0   2.18     0  0.458  7.147  54.2
..       ...   ...    ...   ...    ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1
502  0.04527   0.0  11.93     0  0.573  6.120  76.7
503  0.06076   0.0  11.93     0  0.573  6.976  91.0
504  0.10959   0.0  11.93     0  0.573  6.794  89.3
505  0.04741   0.0  11.93     0  0.573  6.030  80.8

[506 rows x 7 columns]

In [7]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [8]:
X_train,x_test,y_train,y_test=train_test_split(X,y,random_state=1)

In [10]:
std=StandardScaler()
X_train_std=std.fit_transform(X_train)
x_teat_std = std.transform(x_test)

In [18]:
alphas=10 ** np.arange(1,5)
print("diiff alppha val",alphas)

diiff alppha val [   10   100  1000 10000]


In [20]:
ridge_wight=[]
for alpha in alphas:
    ridge= Ridge(alpha=alpha,fit_intercept=True)
    ridge.fit(X_train_std,y_train)
    ridge_wight.append(ridge.coef_)

In [21]:
ridge_wight


[array([-1.49246448,  0.37088936, -0.70836731,  1.08568161, -0.80970633,
         4.4075122 , -0.80450999]),
 array([-1.30486468,  0.5170331 , -0.85951603,  0.96594376, -0.81006847,
         3.54696735, -0.74796938]),
 array([-0.6486645 ,  0.4993468 , -0.67576213,  0.39800779, -0.61503278,
         1.33852138, -0.56022566]),
 array([-0.11842591,  0.11262874, -0.1443168 ,  0.05431575, -0.13553009,
         0.20563081, -0.12574102])]